import "./globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Deep404",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
